// <auto-generated />
namespace MRSkipsAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_weight_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_weight_type));
        
        string IMigrationMetadata.Id
        {
            get { return "202010240950223_change_weight_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
